---
name: Build and Push data pipeline image to AWS ECR
on:
  push:
    branches: [ main ]
    paths:
        - pipelines/data_pipeline/*
        - .github/workflows/push_to_ecr_data_pipeline.yaml
jobs:
  build-and-push-image:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.increment-git-tag.outputs.git-tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: 'coderkol95/AWS_Sagemaker'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DATA_PIPE_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.DATA_PIPE_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./build/git_update.sh -v patch

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: data-pipeline
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      working-directory: pipelines/data_pipeline

  update-lambda:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: 'coderkol95/AWS_Sagemaker'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LAMBDA_UPDATE_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.LAMBDA_UPDATE_SECRET_KEY }}
        aws-region: us-east-1
    - name: Setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install boto3
    - name: Update lambda
      env:
        IMAGE_TAG: ${{ needs.build-and-push-image.outputs.output }}
      run: python update_lambda.py
      working-directory: pipelines/data_pipeline
  
  preprocess-data:
    needs: [update-lambda]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: 'coderkol95/AWS_Sagemaker'
    - name: Setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install boto3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TRIGGER_S3_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.TRIGGER_S3_SECRET_KEY }}
        aws-region: us-east-1 
    - name: Trigger preprocessing job
      run: python upload_dummy_to_s3.py
      working-directory: pipelines/data_pipeline
  
